spring.application.name=Servicio de busqueda
supabase.url=https://rxaqxxcqqfbxctxzxbwi.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YXF4eGNxcWZieGN0eHp4YndpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzE5NDgzOSwiZXhwIjoyMDcyNzcwODM5fQ.fmVVss6R2cKCJ4V2rKL5lpClOMFLmZUNE7Oy-MjpacE

# Puerto personalizado para el microservicio de búsqueda
server.port=3004
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration